# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - acrwebapp01

on:
  push:
    branches:
      - 5.7
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://cliazuacr01.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_199461288ce349bc89a77d665e181fd7 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_51a801b681a24045a432e005d3c24c3c }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: cliazuacr01.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_199461288ce349bc89a77d665e181fd7 }}/shopware:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'acrwebapp01'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_038d5b766f0348d6b9787cb49f823c0e }}
        images: 'cliazuacr01.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_199461288ce349bc89a77d665e181fd7 }}/shopware:${{ github.sha }}'